### ISSUE TITLE
i got this error

### ISSUE THREAD

**Issue by TonyK-T** [TachibanaYoshino/AnimeGAN#10]
File "D:\develop\workspace\AnimeGAN\AnimeGAN.py", line 232, in train
    anime, anime_smooth, real = self.sess.run([anime_img_op, anime_smooth_op, real_img_op])

tensorflow.python.framework.errors_impl.InvalidArgumentError: [_Derived_]buffer_size must be greater than zero.
         [[{{node OptimizeDataset/ShuffleDataset}}]]
         [[OneShotIterator]]

**Comment by TachibanaYoshino** [comment]
Check the data loader and note the batch size

**Comment by jaysimon** [comment]
@TonyK-T  Have you solved the problem? I met this too.
