### ISSUE TITLE
Confuse with ConvBlock(K1,S1) in DSConv.

### ISSUE THREAD

**Issue by Eddy-W** [TachibanaYoshino/AnimeGAN#15]
When I read your paper, I found ConvBlock(K1,S1) in DSConv.
![image](https://user-images.githubusercontent.com/7567546/78900957-30cd2080-7aaa-11ea-9f35-2217534efb2b.png)
But I couldn't find ConvBlock(K1,S1) in your structure of networks.
```python
def Separable_conv2d(inputs, filters, kernel_size=3, strides=1, padding='VALID', Use_bias = None):
    if kernel_size==3 and strides==1:
        inputs = tf.pad(inputs, [[0, 0], [1, 1], [1, 1], [0, 0]], mode="REFLECT")
    if strides == 2:
        inputs = tf.pad(inputs, [[0, 0], [0, 1], [0, 1], [0, 0]], mode="REFLECT")
    return tf.contrib.layers.separable_conv2d(
        inputs,
        num_outputs=filters,
        kernel_size=kernel_size,
        depth_multiplier=1,
        stride=strides,
        biases_initializer=Use_bias,
        normalizer_fn=tf.contrib.layers.instance_norm,
        activation_fn=lrelu,
        padding=padding)
```
 I thought Separable_conv2d means DSConv block, am I right?
What can I think about this?

Thanks again!

**Comment by TachibanaYoshino** [comment]
DSConv is composed of a point conv (1*1conv, ie. ConvBlock) and a separable conv

**Comment by Eddy-W** [comment]
The implement of `tf.contrib.layers.separable_conv2d` is composed of a depthwise conv and a point conv. I figure out. Thanks.
