### ISSUE TITLE
Upgrade with newer tensorflow version

### ISSUE THREAD

**Issue by zerollzeng** [TachibanaYoshino/AnimeGAN#18]
Hi @TachibanaYoshino , your animegan is amazing, thanks for your great works!
Could you consider upgrade this repo with newer tensorflow version, eg. 1.14 or 1.15. since tensorflow 1.8 only support cuda to 9.x version, but cuda 9.x does not supppot newer nvidia rtx graphic card like rtx 2080ti, I run into this problem and it stuck me for a few days. here are to reference:

https://stackoverflow.com/questions/50622525/which-tensorflow-and-cuda-version-combinations-are-compatible

https://github.com/tensorflow/tensorflow/issues/23341

btw here are error output when train animegan in my 2080ti cuda9.0 machine:
```

# ignore...

2020-04-20 11:45:56.252939: E tensorflow/stream_executor/cuda/cuda_blas.cc:654] failed to run cuBLAS routine cublasSgemm_v2: CUBLAS_STATUS_EXECUTION_FAILED
Traceback (most recent call last):
  File "/home/bigdata/anaconda3/envs/animegan/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/bigdata/anaconda3/envs/animegan/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/bigdata/anaconda3/envs/animegan/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : m=65536, n=128, k=64

# ignore
```

**Comment by TachibanaYoshino** [comment]
Hello, I'm glad you paid attention to my work. However, I'm sorry, because I don't have a 2080ti GPU, so the version update cannot be performed. In fact, the new style dataset and the new version of animigan (animegan+) have not been researched and released due to lack of hosts.

**Comment by zerollzeng** [comment]
That's fine, you don't need a 2080ti gpu to upgrade tensorflow version, just install newer tensorflow and see if they work. but it's really a dirty works because of unknown api change. so if you don't have a lots of spare time. just ignore it :dancers:

**Comment by TachibanaYoshino** [comment]
> That's fine, you don't need a 2080ti gpu to upgrade tensorflow version, just install newer tensorflow and see if they work. but it's really a dirty works because of unknown api change. so if you don't have a lots of spare time. just ignore it 👯

tensorflow-1.15.0 is compatible with the code of this repository. In this version, you can run this code without any modification. The premise is that the CUDA and cudnn corresponding to the tf version are correctly installed. Maybe the versions between tf-1.8.0 and tf-1.15.0 are also supported and compatible with this repository, but I didn’t make too many extra attempts.
