### ISSUE TITLE
There are artifacts on generated image

### ISSUE THREAD

**Issue by Chalet37** [TachibanaYoshino/AnimeGAN#19]
I used more shinkai data and real images to train AnimeGAN, and got artifacts on my generated image as follow
![image](https://user-images.githubusercontent.com/8428787/80185196-870b9900-863e-11ea-8066-4e4eec3ff8c5.png)
![image](https://user-images.githubusercontent.com/8428787/80185338-c3d79000-863e-11ea-9293-1573a11fcf47.png)

I trained the model with default parameters in your main.py

I simply removed instance norm according to stylegan2. Not worked.

I was wondering if you had encountered this and what was the solution? thanks

**Comment by TachibanaYoshino** [comment]
As mentioned in StyleGAN2, you can try to replace Instance norm in the generator by **weight demodulation**.

**Comment by Chalet37** [comment]
> As mentioned in StyleGAN2, you can try to replace Instance norm in the generator by **weight demodulation**.

thanks

**Comment by Johnson-yue** [comment]
> As mentioned in StyleGAN2, you can try to replace Instance norm in the generator by **weight demodulation**.

Did you finish it?
