### ISSUE TITLE
i cant replicate the result with hayao.

### ISSUE THREAD

**Issue by LorenzoPanico** [TachibanaYoshino/AnimeGAN#2]
the result are just like a filtered pic.

i tried both checkpoints:

 Haoyao-style.zip

 Haoyao-style-initial-checkpoint.zip

**Comment by LorenzoPanico** [comment]
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/profiler/internal/flops_registry.py:142: tensor_shape_from_node_def_name (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.tensor_shape_from_node_def_name`
209 ops no flops stats due to incomplete shapes.
Parsing Inputs...
Incomplete shape.

**Comment by LorenzoPanico** [comment]
sorry i made a mistake.

**Comment by Johnson-yue** [comment]
@lorrp1 hi, do you replicate the result ?? I can not load AnimeGAN.model-60 weight by tf.train.get_check_state   

In my way:
download:  Haoyao-style.zip 
and unzip into "checkpoint/"
so, the checkpoint folder including:
> checkpoint
> AnimeGAN.model-60.index
> AnimeGAN.model-60.meta
> AnimeGAN.model-60.data-00000-of-00001

and using test scripts:
`python test.py --checkpoint_dir checkpoint/AnimeGAN.model-60 --test_dir dataset/test/real --style_name H`

but it failed
`ckpt is None by tf.train.get_check_state(checkpoint/AnimeGAN.model-60)`

**Comment by lorrp1** [comment]
yeah.

but results are not that good when i try to process low-quality images
