### ISSUE TITLE
can you tell me this project's license?

### ISSUE THREAD

**Issue by kiddingkilling** [TachibanaYoshino/AnimeGAN#20]

**Comment by TachibanaYoshino** [comment]
For academic exchange only, not for commercial use

**Comment by kiddingkilling** [comment]
thank u for your reply

**Comment by kiddingkilling** [comment]
We can offer you some conditions,I hope that you can consider about it. if If  you allow, please provide some contact information

**Comment by TachibanaYoshino** [comment]
If you have any commercial use, please contact via email ghj9527@163.com and explain in detail.
