### ISSUE TITLE
Error happend : buffer_size must be greater than zero.

### ISSUE THREAD

**Issue by tomjerrygithub** [TachibanaYoshino/AnimeGAN#22]
How to fix this ?
and you did a great work ! it's very fun ! Thanks!

> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "main.py", line 112, in <module>
>     main()
>   File "main.py", line 104, in main
>     gan.train()
>   File "/home/tom/workspace/AnimeGAN/AnimeGAN.py", line 232, in train
>     anime, anime_smooth, real = self.sess.run([anime_img_op, anime_smooth_op, real_img_op])
>   File "/root/anaconda3/envs/testa/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
>     run_metadata_ptr)
>   File "/root/anaconda3/envs/testa/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/root/anaconda3/envs/testa/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
>     run_metadata)
>   File "/root/anaconda3/envs/testa/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: buffer_size must be greater than zero.
>          [[Node: ShuffleDataset = ShuffleDataset[output_shapes=[[]], output_types=[DT_FLOAT], reshuffle_each_iteration=true](RepeatDataset, ShuffleDataset/buffer_size, ShuffleDataset/seed, ShuffleDataset/seed2)]]
>          [[Node: OneShotIterator = OneShotIterator[container="", dataset_factory=_make_dataset_25WVjNoEiQY[], output_shapes=[<unknown>, <unknown>], output_types=[DT_FLOAT, DT_FLOAT], shared_name="", _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by TachibanaYoshino** [comment]
Check configuration parameters and data paths.

**Comment by tomjerrygithub** [comment]
> Check configuration parameters and data paths.

Ok，i will try ，thanks  ，and  i send three more questions to your  163.com  email.（before get this answer）
looking forward to reply  thanks~

**Comment by TachibanaYoshino** [comment]
I will reply here. I usually use English and Japanese for academic research and communication, so I rarely use Chinese. 1. I don't have the data about indoors and people. You need to collect it yourself. 2. The vgg model is enough, and other models such as resnet, inception, etc. have little effect on the results. 3. There are four styles in the data set I provided, including Hayao Miyazaki, which came from the movie **The Wind Rises**.

**Comment by tomjerrygithub** [comment]
i have checked configuration parameters , i did not change anyone after download from git.
datapath   ./dataset/Hayao/smooth/*.jpg    ./dataset/Hayao/style/*.jpg

**Comment by tomjerrygithub** [comment]
Thanks    Solved 
 datapath  error
