### ISSUE TITLE
Tips on training on new dataset

### ISSUE THREAD

**Issue by HanYangZhao** [TachibanaYoshino/AnimeGAN#24]
Hi,

Love the work! I have managed to train the model with the existing dateset.  I want to train it to generate better images with people. As you suggested, I've added about 2000 photos of various people in the train_photo. However it looks like the discriminator loss is converging to 0 after a few epoch and the generator loss gets stuck at a high number when I retrain the model.

This seems to be the discriminator is learning too fast? Any parameter I should tune or is my choice of data not good enough?
Am I suppose to replace the photos in the train_photo folder or just add new ones?

Excuse me if this sounds really amateurish, I'm quite new at this.

**Comment by TachibanaYoshino** [comment]
Only the face photos should be in the training photos, and the style data should also be anime faces of the same style.

**Comment by HanYangZhao** [comment]
Thanks! Should I be retraining from scratch or from the initial checkpoint if I want to use the Hayao style?

**Comment by TachibanaYoshino** [comment]
Both are OK

**Comment by tomjerrygithub** [comment]
> Only the face photos should be in the training photos, and the style data should also be anime faces of the same style.

 Can you elaborate more about this ?
“Only the face photos”  it's just like mtcnn crop the face  or just contain face ?
 Can I add 3000 real human faces and cartoon faces in **The Wind Rising** to train together in the current data set?

**Comment by haozihao** [comment]
oh,When I do face model training,I encountered the same problem：the discriminator loss is converging to 0 after a few epoch and the generator loss gets stuck at a high number,more than 1000.

**Comment by HanYangZhao** [comment]
I tried @TachibanaYoshino's suggestion to only use face photos in the training set and it does seem to work

**Comment by haozihao** [comment]
> I tried @TachibanaYoshino's suggestion to only use face photos in the training set and it does seem to work

Did you add some anime face in style folder?

**Comment by HanYangZhao** [comment]
No i used the original file from the wind rises
