### ISSUE TITLE
please add function: output pb file

### ISSUE THREAD

**Issue by tankfly2014** [TachibanaYoshino/AnimeGAN#27]
please add function: output pb file

I do it,but I don't how do. (convert checkpoint to pb file)

do you open a message about convert OR add output pb file function.
=================

example other software message(convert checkpoint to pb file message):

input = tf.placeholder(tf.float32, shape=[None, 36], name="Input")
output = tf.layers.dense(inputs=self.layer2, units=1, activation=tf.nn.relu, name="Prediction")
-------------------
---------------------------------------------------------------------------------------------------------------------------------------------
0: op name = import/Input, op type = ( Placeholder ), inputs = , outputs = import/Input:0
@input shapes:
@output shapes:
name = import/Input:0 : (?, 36)
---------------------------------------------------------------------------------------------------------------------------------------------

19: op name = import/Prediction, op type = ( Relu ), inputs = import/add_5:0, outputs = import/Prediction:0
@input shapes:
name = import/add_5:0 : (?, 1)
@output shapes:
name = import/Prediction:0 : (?, 1)
-----------

**Comment by TachibanaYoshino** [comment]
The weights of the pre-trained model given earlier is the parameter model of the entire network, where the VGG parameter occupies most of the space. Later, I will extract the weight of the pre-trained generator. The weight model is small in size and convenient to call. For the conversion of pb format, I have no more suggestions.

**Comment by tankfly2014** [comment]
thank you. I read VGG image.you are right and good.
