### ISSUE TITLE
hello~how

### ISSUE THREAD

**Issue by YIMI-0901** [TachibanaYoshino/AnimeGAN#28]

**Comment by YIMI-0901** [comment]
how to use tensorflow-gpu to run it?

**Comment by UnlightedOtaku** [comment]
if you have only 1 gpu,change the code in main.py
`# os.environ["CUDA_VISIBLE_DEVICES"] = "1"`
`os.environ["CUDA_VISIBLE_DEVICES"] = "0"`
i don't know why author  use 1 in main and use 0 in test

**Comment by tankfly2014** [comment]
author  computer is two card  and use devices=1.haha
