### ISSUE TITLE
 No module named 'Brightness_tool'

### ISSUE THREAD

**Issue by omi-akif** [TachibanaYoshino/AnimeGAN#30]
With all due respect, I believe the Brightness_tool directory needs to be outside the AnimeGAN+ directory. I tried to resolve the issue by introducing the __init__.py file, but that did not work. I am not really good at python. But after the commit 4 hours ago, the code does not run until and unless I put the Brightness_tool directory outside of AnimeGAN+.

**Comment by TachibanaYoshino** [comment]
Yes, you are right. I know this question. I haven't had time to correct it yesterday. I will correct this problem. Thank you.
