### ISSUE TITLE
val group test_real_A ram very high

### ISSUE THREAD

**Issue by tankfly2014** [TachibanaYoshino/AnimeGAN#32]
I try move to iphone. I test it.  ram very high.The system crashed.   
I just used the verification part, but looking at the structure it seems to call the original training program. This may be the reason for his large memory requirements?
-------------------------------------
I tried trimming the model to make it smaller, but I failed. Do you have a plan to reduce memory（low)?
example:
self.test_generated = self.generator(self.test_real, reuse=**False**)
Of course I failed, the system reported an error
----------------------------------------

In addition, I have run other gan projects, the memory requirements are not so large, why is this project so high memory requirements? Even outside of training, test part of application part

**Comment by TachibanaYoshino** [comment]
Only the weight of the generator is extracted. I don't know how you are doing it, maybe I can't provide more advice.
