### ISSUE TITLE
A JavaScript implementation is available

### ISSUE THREAD

**Issue by TonyLianLong** [TachibanaYoshino/AnimeGAN#33]
Hi @TachibanaYoshino ,

Wonderful work! AnimeGAN is really amazing to me. Those images on the README looks really good. However, for those people who do not have a lot of knowledge in the field of deep learning or even Python but just want to use the work to create an animated version of their photos, installing Tensorflow on a platform such as Windows/Linux could be challenging, which can limit people's enthusiasm. Therefore, from the pre-trained model that you released, I migrated AnimeGAN onto TensorFlow.js, allowing anyone who is able to access the Internet through a browser to do photo animation.

The project is here: https://github.com/TonyLianLong/AnimeGAN.js.
You can have a try here: https://animegan.js.org/.

The implementation uses WebGL or, if not supported, other backends to accelerate computing, but does not require the user to install anything.

Writing this message, I wonder if it's possible that you add a link of AnimeGAN.js to AnimeGAN's README as a demo, which will benefit this project since people are able to upload their own photo and try AnimeGAN out in their browser in addition to viewing the examples that you give, and they will have a deeper feeling than viewing a collection of example images. By listing a demo link, I mean in a way that [this project](https://greentreesnakes.readthedocs.io/en/latest/tofrom.html#going-backwards) lists other implementations, but suggestions are always welcomed. If you'd like, we could discuss further steps and work together.

**Comment by TonyLianLong** [comment]
Thank you so much! Be sure to notify me when you release AnimeGAN+, and I'll create a demo for it too.

**Comment by TachibanaYoshino** [comment]
Thank you very much for your implementation, this is a very contributive work. Great! I have added it. In fact, I will optimize AnimeGAN again to solve the problem of artifacts in the generated image. Currently, in addition to Hayao's style data, other style data needs to be reworked in order to expect better results.

**Comment by TachibanaYoshino** [comment]
This website sometimes times out and cannot be connected. Are there restrictions on multi-user parallel processing?

**Comment by TonyLianLong** [comment]
I use Github Pages to serve my website, and I don't think it has issues with multiple users accessing the website. However, if you are in area which does not have good connection to Github, it could be slow.

**Comment by TonyLianLong** [comment]
For area such as mainland China, I have a separate link which has not been tested much but seems to work: https://longlian.gitee.io/ .

**Comment by TachibanaYoshino** [comment]
> I use Github Pages to serve my website, and I don't think it has issues with multiple users accessing the website. However, if you are in area which does not have good connection to Github, it could be slow.

Yes, I get it. Maybe you should take a break now.
