### ISSUE TITLE
gpu ram and batch

### ISSUE THREAD

**Issue by tankfly2014** [TachibanaYoshino/AnimeGAN#34]
I use 1070 8gb.
I try batch is 2. ok
I try batch is 3. ok
I try batch is 4. overflow.

Is the author's video memory 8gb? Is it higher (11gb)? The author uses batch = 4, will it report an error? Is my graphics card set incorrectly?

**Comment by TachibanaYoshino** [comment]
A borrowed 1080ti was used. Please check your GPU usage.
