### ISSUE TITLE
frozen graph or onnx

### ISSUE THREAD

**Issue by ak9250** [TachibanaYoshino/AnimeGAN#38]
can the weights be exported to a frozen_graph.pb or model.onnx file?

**Comment by TachibanaYoshino** [comment]
Sure, this is very simple. I will give the ckpt_to_pb.py and inference_by_pb.py for you.

**Comment by TachibanaYoshino** [comment]
For onnx file, you can learn it from [here](https://github.com/onnx/tutorials/blob/master/tutorials/OnnxTensorflowExport.ipynb)

**Comment by ak9250** [comment]
@TachibanaYoshino Thanks can you please share the  ckpt_to_pb.py and inference_by_pb.py or the frozen_graph.pb file, will it be small enough to fit under 10mb?

**Comment by TachibanaYoshino** [comment]
What is your email address? I will send you 2 files. But there is a problem with the second file, I believe you can solve it. This is why I did not release them. I don't have time to deal with these problems.

**Comment by ak9250** [comment]
can you add them here as attachment? I can take a look and see and then possibly fix them and then create a pull request if anyone else also needs those files

**Comment by ak9250** [comment]
@TachibanaYoshino you can send to ahsen.khaliq@gmail.com if you prefer that though

**Comment by ak9250** [comment]
@TachibanaYoshino can you send the files to ahsen.khaliq@gmail.com thanks

**Comment by ak9250** [comment]
@TachibanaYoshino can you send the files to ahsen.khaliq@gmail.com thanks
