### ISSUE TITLE
I want to ask about something involving copyright

### ISSUE THREAD

**Issue by snowflowersnowflake** [TachibanaYoshino/AnimeGAN#39]
三次元风景照秒变宫崎骏动画，还能把石原里美带入吉卜力世界，AnimeGAN已开源 - 量子位的文章 - 知乎
https://zhuanlan.zhihu.com/p/118538002

A research from WHU reported by this public account involves the project and is suspected of infringement. May I ask if it is the research involving the author of the project.

**Comment by TachibanaYoshino** [comment]
Their report sought my consent in advance.

**Comment by snowflowersnowflake** [comment]
ic，hence you are the Xin Chen
