### ISSUE TITLE
inference time so slow?

### ISSUE THREAD

**Issue by trangtv57** [TachibanaYoshino/AnimeGAN#46]
hi,
I am not sure where i'm wrong but when i try inference with test.py file  as read.me file, each image need more  than 2 second for build fake images. When reading your paper, image inference just 50ms, what im wrong.  Does image size has big impact for slow inference,
thanks you.

**Comment by hellochy** [comment]
请问这个问题解决了吗，我执行test，单张图片的推理时延y也在3,4秒左右

**Comment by TachibanaYoshino** [comment]
What the paper mentioned is the statistical time of the test dataset images, which is the average value. The size of the image will affect the inference time, especially when the GPU starts inference for the first time.
