### ISSUE TITLE
Baidu and vgg19.npy links are dead 

### ISSUE THREAD

**Issue by haikuoyao** [TachibanaYoshino/AnimeGAN#5]
Hi, 
What a great work!
Those results look really amazing.

Seems Baidu and vgg19.npy links are dead. I can't download them.
Can you reupload them?

Thanks.

**Comment by fengredrum** [comment]
Very impressive work!
Could you upload the data set to google drive?
Baidu link is dead again😂

**Comment by biswaroop1547** [comment]
Please upload the baidu link again, really wanna try this!

**Comment by TachibanaYoshino** [comment]
hi all， Baidu Cloud Storage always fails to review my data files, which makes me uncomfortable. Because the Chinese government controls the Internet connection and does not allow citizens to access international good sites such as Google YouTube, I do not have a VPN to connect to Google Cloud Disk. I'm trying to upload data, such as trying it by email.

**Comment by fengredrum** [comment]
Have you tried encrypting the video before uploading it to Baidu Cloud? @TachibanaYoshino 
Well, you can give us the password here~
I don't think Baidu is capable of cracking every encrypted zip files in its cloud😂😂😂

**Comment by Eskat0n** [comment]
@TachibanaYoshino can you send me an email: muyou.prj@gmail.com
I think I can host these files for you and there's definitely a way to upload them even from behind your firewall.

**Comment by TachibanaYoshino** [comment]
> @TachibanaYoshino can you send me an email: [muyou.prj@gmail.com](mailto:muyou.prj@gmail.com)
> I think I can host these files for you and there's definitely a way to upload them even from behind your firewall.

dataset was uploaded by release, my email was given in paper and the new question, if there are any questions, contact me by email. thanks very much！

**Comment by ilopezfr** [comment]
For those of you that need to download the **vgg19.npy** weights, I'm temporarily sharing the link to my Google Drive until @TachibanaYoshino is able to host it again.  

https://drive.google.com/open?id=1U5HCRpZWAbDVLipNoF8t0ZHpwCRX7kdF

**Comment by TachibanaYoshino** [comment]
> For those of you that need to download the **vgg19.npy** weights, I'm temporarily sharing the link to the file in my Google Drive until @TachibanaYoshino is able to host it again.
> 
> https://drive.google.com/open?id=1U5HCRpZWAbDVLipNoF8t0ZHpwCRX7kdF

thank you！  vgg19.npy and other types of pre-trained parameter models can be found in the official library of GitHub, for example, there are released resources in the official classic network library of tensorflow. I will re-upload vgg19.npy to this library by releasing it.

**Comment by TachibanaYoshino** [comment]
> Please upload the baidu link again @TachibanaYoshino , really wanna try this!

Did you get the data set just now

**Comment by biswaroop1547** [comment]
Yes @TachibanaYoshino got it. Thanks!

**Comment by ptuls** [comment]
Hey guys, here's a GDrive link for the datasets and the **vgg.npy** weights in case the Baidu link goes down: https://drive.google.com/open?id=1clHfhvdU60ghC2R4Zq5omFoElzYTwkMe

P.S. Thanks for this @TachibanaYoshino! Hope you guys are staying safe in Wuhan!

**Comment by iwanttobeabigone** [comment]
@TachibanaYoshino 
Hello, the results seem to be very good. I also want to try training, but I can't access the Google website, can you send me a dataset: 1192690582@qq.com, thanks ~~

**Comment by haikuoyao** [comment]
@TachibanaYoshino 

Thanks a lot. 

GREAT work
