### ISSUE TITLE
Contact me, there is my Email (that is *** 9527 @ **) in the paper in the doc directory in the library.

### ISSUE THREAD

**Issue by TachibanaYoshino** [TachibanaYoshino/AnimeGAN#7]
Contact me, there is my Email (that is *** 9527 @ **) in the paper in the doc directory in the library. I think you can contact us through the emails provided if you have any data set problems. I am sorry that due to the plague in Wuhan, China, I was forced to stay in my rural hometown. My home does not have broadband internet and I cannot go online frequently.

**Comment by Johnson-yue** [comment]
武汉解封在即，开学已经不远了，主要是百度云总把数据集的链接封掉，要不然也不能有这么关于数据集的issue，感谢分享！！
